// <auto-generated />
namespace Ises.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Version_101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version_101));
        
        string IMigrationMetadata.Id
        {
            get { return "201509191301359_Version_1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
